// Generated by scripts/build-front.mjs. Do not edit directly.
// Template SHA-256: 116b4b0db0feffd6575b98ef5fa6066459f9cf57b98dd61820aab21d6b68c49a
window.GpuMonitorRender = ((Vue) => {
const { resolveComponent: _resolveComponent, createVNode: _createVNode, withCtx: _withCtx, createElementVNode: _createElementVNode, toDisplayString: _toDisplayString, openBlock: _openBlock, createElementBlock: _createElementBlock, createCommentVNode: _createCommentVNode, createBlock: _createBlock, normalizeClass: _normalizeClass, renderList: _renderList, Fragment: _Fragment, createTextVNode: _createTextVNode, withModifiers: _withModifiers, normalizeStyle: _normalizeStyle } = Vue

const _hoisted_1 = { class: "command-bar" }
const _hoisted_2 = { class: "brand-block" }
const _hoisted_3 = {
  class: "brand-mark",
  "aria-hidden": "true"
}
const _hoisted_4 = { class: "brand-copy" }
const _hoisted_5 = {
  key: 0,
  class: "node-context"
}
const _hoisted_6 = { class: "eyebrow" }
const _hoisted_7 = { class: "command-actions" }
const _hoisted_8 = { key: 0 }
const _hoisted_9 = { class: "node-select-control" }
const _hoisted_10 = { class: "sr-only" }
const _hoisted_11 = { class: "refresh-control" }
const _hoisted_12 = {
  key: 0,
  class: "state-panel state-panel--blocking"
}
const _hoisted_13 = {
  key: 0,
  class: "inline-alert",
  role: "alert"
}
const _hoisted_14 = { class: "inline-alert__icon" }
const _hoisted_15 = { class: "inline-alert__content" }
const _hoisted_16 = {
  class: "dashboard-section split-layout",
  "aria-labelledby": "resources-title"
}
const _hoisted_17 = { class: "panel resource-panel" }
const _hoisted_18 = { class: "panel-heading" }
const _hoisted_19 = { id: "resources-title" }
const _hoisted_20 = { class: "resource-meter" }
const _hoisted_21 = { class: "resource-meter__header" }
const _hoisted_22 = { class: "resource-meter" }
const _hoisted_23 = { class: "resource-meter__header" }
const _hoisted_24 = { class: "network-grid" }
const _hoisted_25 = { class: "network-stat" }
const _hoisted_26 = { class: "network-stat" }
const _hoisted_27 = {
  class: "panel trend-panel",
  "aria-labelledby": "trend-title"
}
const _hoisted_28 = { class: "panel-heading" }
const _hoisted_29 = { id: "trend-title" }
const _hoisted_30 = { class: "trend-heading-right" }
const _hoisted_31 = { class: "trend-range-bar" }
const _hoisted_32 = {
  key: 0,
  class: "trend-waiting"
}
const _hoisted_33 = {
  key: 1,
  class: "trend-content"
}
const _hoisted_34 = {
  class: "trend-legend",
  "aria-label": "Legend"
}
const _hoisted_35 = ["aria-label"]
const _hoisted_36 = ["y1", "y2"]
const _hoisted_37 = ["points"]
const _hoisted_38 = {
  key: 0,
  class: "trend-hover-layer"
}
const _hoisted_39 = ["x1", "x2"]
const _hoisted_40 = ["cx", "cy"]
const _hoisted_41 = {
  key: 2,
  class: "trend-waiting"
}
const _hoisted_42 = {
  class: "dashboard-section",
  "aria-labelledby": "system-process-title"
}
const _hoisted_43 = { class: "panel system-process-panel" }
const _hoisted_44 = { class: "system-process-heading" }
const _hoisted_45 = { class: "process-title" }
const _hoisted_46 = { id: "system-process-title" }
const _hoisted_47 = { key: 0 }
const _hoisted_48 = { key: 1 }
const _hoisted_49 = { class: "system-process-note" }
const _hoisted_50 = {
  key: 0,
  class: "desktop-process-table"
}
const _hoisted_51 = ["title"]
const _hoisted_52 = {
  key: 1,
  class: "desktop-process-table"
}
const _hoisted_53 = {
  key: 2,
  class: "mobile-process-list"
}
const _hoisted_54 = {
  key: 0,
  class: "empty-inline"
}
const _hoisted_55 = { class: "process-card__head" }
const _hoisted_56 = ["title"]
const _hoisted_57 = { class: "process-command" }
const _hoisted_58 = {
  key: 3,
  class: "mobile-process-list"
}
const _hoisted_59 = {
  key: 0,
  class: "empty-inline"
}
const _hoisted_60 = { class: "process-card__head" }
const _hoisted_61 = {
  class: "dashboard-section",
  "aria-labelledby": "gpu-title"
}
const _hoisted_62 = { class: "section-heading section-heading--inline" }
const _hoisted_63 = { id: "gpu-title" }
const _hoisted_64 = { class: "count-badge" }
const _hoisted_65 = {
  key: 0,
  class: "gpu-list"
}
const _hoisted_66 = { class: "gpu-header" }
const _hoisted_67 = { class: "gpu-header-left" }
const _hoisted_68 = { class: "gpu-index" }
const _hoisted_69 = { class: "status-tag-content" }
const _hoisted_70 = { class: "gpu-body" }
const _hoisted_71 = { class: "gpu-workload" }
const _hoisted_72 = { class: "workload-item" }
const _hoisted_73 = { class: "workload-header" }
const _hoisted_74 = { class: "workload-item" }
const _hoisted_75 = { class: "workload-header" }
const _hoisted_76 = { class: "sensor-grid" }
const _hoisted_77 = { class: "sensor-stat" }
const _hoisted_78 = { class: "sensor-stat" }
const _hoisted_79 = { class: "sensor-stat" }
const _hoisted_80 = { class: "sensor-stat" }
const _hoisted_81 = { class: "process-title" }
const _hoisted_82 = { class: "desktop-process-table" }
const _hoisted_83 = { class: "mobile-process-list" }
const _hoisted_84 = {
  key: 0,
  class: "empty-inline"
}
const _hoisted_85 = { class: "process-card__head" }
const _hoisted_86 = { class: "process-command" }
const _hoisted_87 = {
  key: 1,
  class: "state-panel"
}
const _hoisted_88 = {
  key: 2,
  class: "loading-layout",
  "aria-label": "Loading"
}
const _hoisted_89 = { class: "skeleton-grid" }
const _hoisted_90 = {
  key: 3,
  class: "state-panel state-panel--blocking"
}
const _hoisted_91 = { class: "footer-copyright" }

return function render(_ctx, _cache) {
  const _component_Monitor = _resolveComponent("Monitor")
  const _component_el_icon = _resolveComponent("el-icon")
  const _component_CircleCheckFilled = _resolveComponent("CircleCheckFilled")
  const _component_WarningFilled = _resolveComponent("WarningFilled")
  const _component_Clock = _resolveComponent("Clock")
  const _component_el_option = _resolveComponent("el-option")
  const _component_el_select = _resolveComponent("el-select")
  const _component_el_switch = _resolveComponent("el-switch")
  const _component_el_button = _resolveComponent("el-button")
  const _component_el_tooltip = _resolveComponent("el-tooltip")
  const _component_el_dropdown_item = _resolveComponent("el-dropdown-item")
  const _component_el_dropdown_menu = _resolveComponent("el-dropdown-menu")
  const _component_el_dropdown = _resolveComponent("el-dropdown")
  const _component_Sunrise = _resolveComponent("Sunrise")
  const _component_Sunny = _resolveComponent("Sunny")
  const _component_Moon = _resolveComponent("Moon")
  const _component_Connection = _resolveComponent("Connection")
  const _component_el_progress = _resolveComponent("el-progress")
  const _component_Download = _resolveComponent("Download")
  const _component_Upload = _resolveComponent("Upload")
  const _component_el_button_group = _resolveComponent("el-button-group")
  const _component_DataLine = _resolveComponent("DataLine")
  const _component_el_table_column = _resolveComponent("el-table-column")
  const _component_el_table = _resolveComponent("el-table")
  const _component_el_collapse_item = _resolveComponent("el-collapse-item")
  const _component_el_collapse = _resolveComponent("el-collapse")
  const _component_el_tag = _resolveComponent("el-tag")
  const _component_el_skeleton_item = _resolveComponent("el-skeleton-item")
  const _component_el_skeleton = _resolveComponent("el-skeleton")

  return (_openBlock(), _createElementBlock(_Fragment, null, [
    _createElementVNode("header", _hoisted_1, [
      _createElementVNode("div", _hoisted_2, [
        _createElementVNode("div", _hoisted_3, [
          _createVNode(_component_el_icon, null, {
            default: _withCtx(() => [
              _createVNode(_component_Monitor)
            ]),
            _: 1 /* STABLE */
          })
        ]),
        _createElementVNode("div", _hoisted_4, [
          _createElementVNode("h1", null, _toDisplayString(_ctx.translate('appTitle')), 1 /* TEXT */),
          _createElementVNode("p", null, _toDisplayString(_ctx.translate('appSubtitle')), 1 /* TEXT */)
        ])
      ]),
      (_ctx.selectedServer)
        ? (_openBlock(), _createElementBlock("div", _hoisted_5, [
            _createElementVNode("span", _hoisted_6, _toDisplayString(_ctx.translate('node')), 1 /* TEXT */),
            _createElementVNode("strong", null, _toDisplayString(_ctx.selectedServer.name), 1 /* TEXT */)
          ]))
        : _createCommentVNode("v-if", true),
      _createElementVNode("div", _hoisted_7, [
        _createElementVNode("div", {
          class: _normalizeClass(["connection-pill", `is-${_ctx.connectionState.key}`]),
          role: "status",
          "aria-live": "polite"
        }, [
          (_ctx.connectionState.icon === 'check')
            ? (_openBlock(), _createBlock(_component_el_icon, { key: 0 }, {
                default: _withCtx(() => [
                  _createVNode(_component_CircleCheckFilled)
                ]),
                _: 1 /* STABLE */
              }))
            : (_ctx.connectionState.icon === 'warning')
              ? (_openBlock(), _createBlock(_component_el_icon, { key: 1 }, {
                  default: _withCtx(() => [
                    _createVNode(_component_WarningFilled)
                  ]),
                  _: 1 /* STABLE */
                }))
              : (_openBlock(), _createBlock(_component_el_icon, {
                  key: 2,
                  class: "is-spinning"
                }, {
                  default: _withCtx(() => [
                    _createVNode(_component_Clock)
                  ]),
                  _: 1 /* STABLE */
                })),
          _createElementVNode("span", null, [
            _createElementVNode("strong", null, _toDisplayString(_ctx.connectionState.label), 1 /* TEXT */),
            (_ctx.lastUpdateTime)
              ? (_openBlock(), _createElementBlock("small", _hoisted_8, _toDisplayString(_ctx.relativeUpdate) + " · " + _toDisplayString(_ctx.lastUpdateTime), 1 /* TEXT */))
              : _createCommentVNode("v-if", true)
          ])
        ], 2 /* CLASS */),
        _createElementVNode("div", _hoisted_9, [
          _createElementVNode("span", _hoisted_10, _toDisplayString(_ctx.translate('selectServer')), 1 /* TEXT */),
          _createVNode(_component_el_select, {
            modelValue: _ctx.selectedServerId,
            "onUpdate:modelValue": _cache[0] || (_cache[0] = $event => ((_ctx.selectedServerId) = $event)),
            placeholder: _ctx.translate('selectServer'),
            onChange: _ctx.handleServerChange,
            "aria-label": _ctx.translate('selectServer')
          }, {
            default: _withCtx(() => [
              (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.servers, (server) => {
                return (_openBlock(), _createBlock(_component_el_option, {
                  key: server.id,
                  label: server.name,
                  value: server.id
                }, null, 8 /* PROPS */, ["label", "value"]))
              }), 128 /* KEYED_FRAGMENT */))
            ]),
            _: 1 /* STABLE */
          }, 8 /* PROPS */, ["modelValue", "placeholder", "onChange", "aria-label"])
        ]),
        _createElementVNode("div", _hoisted_11, [
          _createElementVNode("span", null, _toDisplayString(_ctx.translate('autoRefresh')), 1 /* TEXT */),
          _createVNode(_component_el_switch, {
            modelValue: _ctx.autoRefresh,
            "onUpdate:modelValue": _cache[1] || (_cache[1] = $event => ((_ctx.autoRefresh) = $event)),
            onChange: _ctx.toggleAutoRefresh,
            "aria-label": _ctx.translate('autoRefresh')
          }, null, 8 /* PROPS */, ["modelValue", "onChange", "aria-label"])
        ]),
        _createVNode(_component_el_tooltip, {
          content: _ctx.translate('refresh'),
          placement: "bottom"
        }, {
          default: _withCtx(() => [
            _createVNode(_component_el_button, {
              class: "refresh-button",
              type: "primary",
              icon: _ctx.RefreshIcon,
              loading: _ctx.loading,
              onClick: _ctx.refreshCurrent,
              "aria-label": _ctx.translate('refresh'),
              circle: ""
            }, null, 8 /* PROPS */, ["icon", "loading", "onClick", "aria-label"])
          ]),
          _: 1 /* STABLE */
        }, 8 /* PROPS */, ["content"]),
        _createVNode(_component_el_dropdown, {
          trigger: "click",
          onCommand: _ctx.handleLocaleChange
        }, {
          dropdown: _withCtx(() => [
            _createVNode(_component_el_dropdown_menu, null, {
              default: _withCtx(() => [
                _createVNode(_component_el_dropdown_item, {
                  command: "zh",
                  disabled: _ctx.currentLocale === 'zh'
                }, {
                  default: _withCtx(() => [...(_cache[11] || (_cache[11] = [
                    _createTextVNode("中文", -1 /* CACHED */)
                  ]))]),
                  _: 1 /* STABLE */
                }, 8 /* PROPS */, ["disabled"]),
                _createVNode(_component_el_dropdown_item, {
                  command: "en",
                  disabled: _ctx.currentLocale === 'en'
                }, {
                  default: _withCtx(() => [...(_cache[12] || (_cache[12] = [
                    _createTextVNode("English", -1 /* CACHED */)
                  ]))]),
                  _: 1 /* STABLE */
                }, 8 /* PROPS */, ["disabled"]),
                _createVNode(_component_el_dropdown_item, {
                  command: "ja",
                  disabled: _ctx.currentLocale === 'ja'
                }, {
                  default: _withCtx(() => [...(_cache[13] || (_cache[13] = [
                    _createTextVNode("日本語", -1 /* CACHED */)
                  ]))]),
                  _: 1 /* STABLE */
                }, 8 /* PROPS */, ["disabled"])
              ]),
              _: 1 /* STABLE */
            })
          ]),
          default: _withCtx(() => [
            _createVNode(_component_el_button, {
              plain: "",
              "aria-label": _ctx.translate('language')
            }, {
              default: _withCtx(() => [
                _createTextVNode(_toDisplayString(_ctx.localeText), 1 /* TEXT */)
              ]),
              _: 1 /* STABLE */
            }, 8 /* PROPS */, ["aria-label"])
          ]),
          _: 1 /* STABLE */
        }, 8 /* PROPS */, ["onCommand"]),
        _createVNode(_component_el_dropdown, {
          trigger: "click",
          onCommand: _ctx.handleThemeChange
        }, {
          dropdown: _withCtx(() => [
            _createVNode(_component_el_dropdown_menu, null, {
              default: _withCtx(() => [
                _createVNode(_component_el_dropdown_item, {
                  command: "auto",
                  disabled: _ctx.currentTheme === 'auto'
                }, {
                  default: _withCtx(() => [
                    _createVNode(_component_el_icon, null, {
                      default: _withCtx(() => [
                        _createVNode(_component_Sunrise)
                      ]),
                      _: 1 /* STABLE */
                    }),
                    _createTextVNode(_toDisplayString(_ctx.translate('themeMenu.auto')), 1 /* TEXT */)
                  ]),
                  _: 1 /* STABLE */
                }, 8 /* PROPS */, ["disabled"]),
                _createVNode(_component_el_dropdown_item, {
                  command: "light",
                  disabled: _ctx.currentTheme === 'light'
                }, {
                  default: _withCtx(() => [
                    _createVNode(_component_el_icon, null, {
                      default: _withCtx(() => [
                        _createVNode(_component_Sunny)
                      ]),
                      _: 1 /* STABLE */
                    }),
                    _createTextVNode(_toDisplayString(_ctx.translate('themeMenu.light')), 1 /* TEXT */)
                  ]),
                  _: 1 /* STABLE */
                }, 8 /* PROPS */, ["disabled"]),
                _createVNode(_component_el_dropdown_item, {
                  command: "dark",
                  disabled: _ctx.currentTheme === 'dark'
                }, {
                  default: _withCtx(() => [
                    _createVNode(_component_el_icon, null, {
                      default: _withCtx(() => [
                        _createVNode(_component_Moon)
                      ]),
                      _: 1 /* STABLE */
                    }),
                    _createTextVNode(_toDisplayString(_ctx.translate('themeMenu.dark')), 1 /* TEXT */)
                  ]),
                  _: 1 /* STABLE */
                }, 8 /* PROPS */, ["disabled"])
              ]),
              _: 1 /* STABLE */
            })
          ]),
          default: _withCtx(() => [
            _createVNode(_component_el_button, {
              plain: "",
              icon: _ctx.themeIcon,
              "aria-label": _ctx.translate('themeLabel')
            }, {
              default: _withCtx(() => [
                _createTextVNode(_toDisplayString(_ctx.themeText), 1 /* TEXT */)
              ]),
              _: 1 /* STABLE */
            }, 8 /* PROPS */, ["icon", "aria-label"])
          ]),
          _: 1 /* STABLE */
        }, 8 /* PROPS */, ["onCommand"])
      ])
    ]),
    _createElementVNode("main", null, [
      (_ctx.configError || (!_ctx.configLoading && _ctx.servers.length === 0))
        ? (_openBlock(), _createElementBlock("section", _hoisted_12, [
            _createVNode(_component_el_icon, null, {
              default: _withCtx(() => [
                _createVNode(_component_WarningFilled)
              ]),
              _: 1 /* STABLE */
            }),
            _createElementVNode("div", null, [
              _createElementVNode("h2", null, _toDisplayString(_ctx.configError ? _ctx.translate('errors.configFailedTitle') : _ctx.translate('errors.noConfigTitle')), 1 /* TEXT */),
              _createElementVNode("p", null, _toDisplayString(_ctx.configError ? _ctx.translate('errors.loadServerList') : _ctx.translate('errors.noConfigDesc')), 1 /* TEXT */)
            ]),
            _createVNode(_component_el_button, {
              type: "primary",
              onClick: _ctx.loadConfig
            }, {
              default: _withCtx(() => [
                _createTextVNode(_toDisplayString(_ctx.translate('retry')), 1 /* TEXT */)
              ]),
              _: 1 /* STABLE */
            }, 8 /* PROPS */, ["onClick"])
          ]))
        : (_ctx.currentData)
          ? (_openBlock(), _createElementBlock(_Fragment, { key: 1 }, [
              (_ctx.nodeError)
                ? (_openBlock(), _createElementBlock("section", _hoisted_13, [
                    _createElementVNode("div", _hoisted_14, [
                      _createVNode(_component_el_icon, null, {
                        default: _withCtx(() => [
                          _createVNode(_component_WarningFilled)
                        ]),
                        _: 1 /* STABLE */
                      })
                    ]),
                    _createElementVNode("div", _hoisted_15, [
                      _createElementVNode("strong", null, _toDisplayString(_ctx.translate('errors.nodeFailedTitle')), 1 /* TEXT */),
                      _createElementVNode("span", null, _toDisplayString(_ctx.translate('errors.nodeFailedDesc')), 1 /* TEXT */)
                    ]),
                    _createVNode(_component_el_button, {
                      plain: "",
                      onClick: _ctx.refreshCurrent
                    }, {
                      default: _withCtx(() => [
                        _createTextVNode(_toDisplayString(_ctx.translate('retry')), 1 /* TEXT */)
                      ]),
                      _: 1 /* STABLE */
                    }, 8 /* PROPS */, ["onClick"])
                  ]))
                : _createCommentVNode("v-if", true),
              _createElementVNode("section", _hoisted_16, [
                _createElementVNode("article", _hoisted_17, [
                  _createElementVNode("div", _hoisted_18, [
                    _createElementVNode("div", null, [
                      _cache[14] || (_cache[14] = _createElementVNode("span", { class: "eyebrow" }, "Telemetry", -1 /* CACHED */)),
                      _createElementVNode("h2", _hoisted_19, _toDisplayString(_ctx.translate('resources.title')), 1 /* TEXT */),
                      _createElementVNode("p", null, _toDisplayString(_ctx.translate('resources.subtitle')), 1 /* TEXT */)
                    ]),
                    _createVNode(_component_el_icon, null, {
                      default: _withCtx(() => [
                        _createVNode(_component_Connection)
                      ]),
                      _: 1 /* STABLE */
                    })
                  ]),
                  _createElementVNode("div", _hoisted_20, [
                    _createElementVNode("div", _hoisted_21, [
                      _createElementVNode("div", null, [
                        _createElementVNode("strong", null, _toDisplayString(_ctx.translate('resources.cpu')), 1 /* TEXT */),
                        _createElementVNode("span", null, _toDisplayString(_ctx.formatFrequency(_ctx.currentData.system.cpu.frequency_current)), 1 /* TEXT */)
                      ]),
                      _createElementVNode("b", null, _toDisplayString(_ctx.formatPercent(_ctx.currentData.system.cpu.percent, 1)), 1 /* TEXT */)
                    ]),
                    _createVNode(_component_el_progress, {
                      percentage: Math.round(_ctx.currentData.system.cpu.percent),
                      "stroke-width": 10,
                      "show-text": false
                    }, null, 8 /* PROPS */, ["percentage"])
                  ]),
                  _createElementVNode("div", _hoisted_22, [
                    _createElementVNode("div", _hoisted_23, [
                      _createElementVNode("div", null, [
                        _createElementVNode("strong", null, _toDisplayString(_ctx.translate('resources.memory')), 1 /* TEXT */),
                        _createElementVNode("span", null, _toDisplayString(_ctx.formatBytes(_ctx.currentData.system.memory.used)) + " / " + _toDisplayString(_ctx.formatBytes(_ctx.currentData.system.memory.total)), 1 /* TEXT */)
                      ]),
                      _createElementVNode("b", null, _toDisplayString(_ctx.formatPercent(_ctx.currentData.system.memory.percent, 1)), 1 /* TEXT */)
                    ]),
                    _createVNode(_component_el_progress, {
                      percentage: Math.round(_ctx.currentData.system.memory.percent),
                      "stroke-width": 10,
                      "show-text": false
                    }, null, 8 /* PROPS */, ["percentage"])
                  ]),
                  _createElementVNode("div", _hoisted_24, [
                    _createElementVNode("div", _hoisted_25, [
                      _createVNode(_component_el_icon, null, {
                        default: _withCtx(() => [
                          _createVNode(_component_Download)
                        ]),
                        _: 1 /* STABLE */
                      }),
                      _createElementVNode("div", null, [
                        _createElementVNode("span", null, _toDisplayString(_ctx.translate('resources.totalReceived')), 1 /* TEXT */),
                        _createElementVNode("strong", null, _toDisplayString(_ctx.formatBytes(_ctx.currentData.system.network.bytes_recv)), 1 /* TEXT */),
                        _createElementVNode("small", null, _toDisplayString(_ctx.translate('resources.recentRate')) + " · " + _toDisplayString(_ctx.networkRates ? _ctx.formatBytes(_ctx.networkRates.received, true) : _ctx.translate('resources.collecting')), 1 /* TEXT */)
                      ])
                    ]),
                    _createElementVNode("div", _hoisted_26, [
                      _createVNode(_component_el_icon, null, {
                        default: _withCtx(() => [
                          _createVNode(_component_Upload)
                        ]),
                        _: 1 /* STABLE */
                      }),
                      _createElementVNode("div", null, [
                        _createElementVNode("span", null, _toDisplayString(_ctx.translate('resources.totalSent')), 1 /* TEXT */),
                        _createElementVNode("strong", null, _toDisplayString(_ctx.formatBytes(_ctx.currentData.system.network.bytes_sent)), 1 /* TEXT */),
                        _createElementVNode("small", null, _toDisplayString(_ctx.translate('resources.recentRate')) + " · " + _toDisplayString(_ctx.networkRates ? _ctx.formatBytes(_ctx.networkRates.sent, true) : _ctx.translate('resources.collecting')), 1 /* TEXT */)
                      ])
                    ])
                  ])
                ]),
                _createElementVNode("article", _hoisted_27, [
                  _createElementVNode("div", _hoisted_28, [
                    _createElementVNode("div", null, [
                      _cache[15] || (_cache[15] = _createElementVNode("span", { class: "eyebrow" }, "Session trend", -1 /* CACHED */)),
                      _createElementVNode("h2", _hoisted_29, _toDisplayString(_ctx.translate('trend.title')), 1 /* TEXT */)
                    ]),
                    _createElementVNode("div", _hoisted_30, [
                      _createElementVNode("div", _hoisted_31, [
                        _createVNode(_component_el_button_group, null, {
                          default: _withCtx(() => [
                            (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.trendRanges, (cfg, key) => {
                              return (_openBlock(), _createBlock(_component_el_button, {
                                key: key,
                                type: _ctx.trendRange === key ? 'primary' : 'default',
                                size: "small",
                                onClick: $event => (_ctx.setTrendRange(key))
                              }, {
                                default: _withCtx(() => [
                                  _createTextVNode(_toDisplayString(_ctx.translate(`trend.ranges.${key}`)), 1 /* TEXT */)
                                ]),
                                _: 2 /* DYNAMIC */
                              }, 1032 /* PROPS, DYNAMIC_SLOTS */, ["type", "onClick"]))
                            }), 128 /* KEYED_FRAGMENT */))
                          ]),
                          _: 1 /* STABLE */
                        })
                      ]),
                      _createVNode(_component_el_icon, null, {
                        default: _withCtx(() => [
                          _createVNode(_component_DataLine)
                        ]),
                        _: 1 /* STABLE */
                      })
                    ])
                  ]),
                  (_ctx.historyLoading)
                    ? (_openBlock(), _createElementBlock("div", _hoisted_32, [
                        _createVNode(_component_el_icon, { class: "is-spinning" }, {
                          default: _withCtx(() => [
                            _createVNode(_component_Clock)
                          ]),
                          _: 1 /* STABLE */
                        }),
                        _createElementVNode("span", null, _toDisplayString(_ctx.translate('trend.loadingHistory')), 1 /* TEXT */)
                      ]))
                    : (_ctx.trendSeries.length)
                      ? (_openBlock(), _createElementBlock("div", _hoisted_33, [
                          _createElementVNode("div", _hoisted_34, [
                            (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.trendSeries, (series) => {
                              return (_openBlock(), _createElementBlock("span", {
                                key: series.key,
                                class: _normalizeClass(`series-${series.key}`)
                              }, [
                                _cache[16] || (_cache[16] = _createElementVNode("i", null, null, -1 /* CACHED */)),
                                _createTextVNode(_toDisplayString(series.label), 1 /* TEXT */)
                              ], 2 /* CLASS */))
                            }), 128 /* KEYED_FRAGMENT */))
                          ]),
                          (_openBlock(), _createElementBlock("svg", {
                            class: "trend-chart",
                            viewBox: "0 0 600 180",
                            preserveAspectRatio: "none",
                            role: "img",
                            "aria-label": _ctx.translate('trend.details'),
                            onMousemove: _cache[2] || (_cache[2] = (...args) => (_ctx.updateTrendHover && _ctx.updateTrendHover(...args))),
                            onMouseleave: _cache[3] || (_cache[3] = (...args) => (_ctx.clearTrendHover && _ctx.clearTrendHover(...args))),
                            onTouchstart: _cache[4] || (_cache[4] = _withModifiers((...args) => (_ctx.updateTrendHover && _ctx.updateTrendHover(...args)), ["prevent"])),
                            onTouchmove: _cache[5] || (_cache[5] = _withModifiers((...args) => (_ctx.updateTrendHover && _ctx.updateTrendHover(...args)), ["prevent"])),
                            onTouchend: _cache[6] || (_cache[6] = (...args) => (_ctx.clearTrendHover && _ctx.clearTrendHover(...args)))
                          }, [
                            (_openBlock(), _createElementBlock(_Fragment, null, _renderList([0, 45, 90, 135, 180], (y) => {
                              return _createElementVNode("line", {
                                key: y,
                                x1: "0",
                                y1: y,
                                x2: "600",
                                y2: y,
                                class: "trend-grid-line"
                              }, null, 8 /* PROPS */, _hoisted_36)
                            }), 64 /* STABLE_FRAGMENT */)),
                            (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.trendSeries, (series) => {
                              return (_openBlock(), _createElementBlock("polyline", {
                                key: series.key,
                                points: series.points,
                                class: _normalizeClass(`trend-line series-${series.key}`)
                              }, null, 10 /* CLASS, PROPS */, _hoisted_37))
                            }), 128 /* KEYED_FRAGMENT */)),
                            (_ctx.activeTrendSample)
                              ? (_openBlock(), _createElementBlock("g", _hoisted_38, [
                                  _createElementVNode("line", {
                                    x1: _ctx.activeTrendSample.x,
                                    y1: "0",
                                    x2: _ctx.activeTrendSample.x,
                                    y2: "180",
                                    class: "trend-crosshair"
                                  }, null, 8 /* PROPS */, _hoisted_39),
                                  (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.activeTrendSample.values, (value) => {
                                    return (_openBlock(), _createElementBlock("circle", {
                                      key: value.key,
                                      cx: _ctx.activeTrendSample.x,
                                      cy: value.y,
                                      r: "5",
                                      class: _normalizeClass(`trend-point series-${value.key}`)
                                    }, null, 10 /* CLASS, PROPS */, _hoisted_40))
                                  }), 128 /* KEYED_FRAGMENT */))
                                ]))
                              : _createCommentVNode("v-if", true)
                          ], 40 /* PROPS, NEED_HYDRATION */, _hoisted_35)),
                          (_ctx.activeTrendSample)
                            ? (_openBlock(), _createElementBlock("div", {
                                key: 0,
                                class: _normalizeClass(["trend-tooltip", { 'is-right': _ctx.activeTrendSample.x > 360 }]),
                                style: _normalizeStyle({ left: _ctx.activeTrendSample.position }),
                                role: "status"
                              }, [
                                _createElementVNode("strong", null, _toDisplayString(_ctx.translate('trend.time')) + " · " + _toDisplayString(_ctx.activeTrendSample.time), 1 /* TEXT */),
                                (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.activeTrendSample.values, (value) => {
                                  return (_openBlock(), _createElementBlock("span", {
                                    key: value.key
                                  }, [
                                    _createElementVNode("i", {
                                      class: _normalizeClass(`series-${value.key}`)
                                    }, null, 2 /* CLASS */),
                                    _createTextVNode(_toDisplayString(value.label), 1 /* TEXT */),
                                    _createElementVNode("b", null, _toDisplayString(value.value), 1 /* TEXT */)
                                  ]))
                                }), 128 /* KEYED_FRAGMENT */))
                              ], 6 /* CLASS, STYLE */))
                            : _createCommentVNode("v-if", true),
                          _cache[17] || (_cache[17] = _createElementVNode("div", { class: "trend-scale" }, [
                            _createElementVNode("span", null, "100%"),
                            _createElementVNode("span", null, "0%")
                          ], -1 /* CACHED */))
                        ]))
                      : (_openBlock(), _createElementBlock("div", _hoisted_41, [
                          _createVNode(_component_el_icon, null, {
                            default: _withCtx(() => [
                              _createVNode(_component_Clock)
                            ]),
                            _: 1 /* STABLE */
                          }),
                          _createElementVNode("span", null, _toDisplayString(_ctx.translate('trend.waiting')), 1 /* TEXT */)
                        ]))
                ])
              ]),
              _createElementVNode("section", _hoisted_42, [
                _createElementVNode("article", _hoisted_43, [
                  _createVNode(_component_el_collapse, { class: "system-process-collapse" }, {
                    default: _withCtx(() => [
                      _createVNode(_component_el_collapse_item, { name: "system-processes" }, {
                        title: _withCtx(() => [
                          _createElementVNode("div", _hoisted_44, [
                            _createElementVNode("span", _hoisted_45, [
                              _createElementVNode("strong", _hoisted_46, _toDisplayString(_ctx.translate('systemProcess.title')), 1 /* TEXT */),
                              (_ctx.systemProcessSort === 'user')
                                ? (_openBlock(), _createElementBlock("span", _hoisted_47, _toDisplayString(_ctx.translate('systemProcess.userCount', _ctx.systemUsers.length)), 1 /* TEXT */))
                                : (_openBlock(), _createElementBlock("span", _hoisted_48, _toDisplayString(_ctx.translate('systemProcess.count', _ctx.sortedSystemProcesses.length, _ctx.systemProcessInstanceCount)), 1 /* TEXT */))
                            ]),
                            _createVNode(_component_el_button_group, {
                              class: "system-process-sort",
                              onClick: _cache[10] || (_cache[10] = _withModifiers(() => {}, ["stop"]))
                            }, {
                              default: _withCtx(() => [
                                _createVNode(_component_el_button, {
                                  size: "small",
                                  type: _ctx.systemProcessSort === 'cpu' ? 'primary' : 'default',
                                  onClick: _cache[7] || (_cache[7] = _withModifiers($event => (_ctx.setSystemProcessSort('cpu')), ["stop"]))
                                }, {
                                  default: _withCtx(() => [
                                    _createTextVNode(_toDisplayString(_ctx.translate('systemProcess.sortCpu')), 1 /* TEXT */)
                                  ]),
                                  _: 1 /* STABLE */
                                }, 8 /* PROPS */, ["type"]),
                                _createVNode(_component_el_button, {
                                  size: "small",
                                  type: _ctx.systemProcessSort === 'memory' ? 'primary' : 'default',
                                  onClick: _cache[8] || (_cache[8] = _withModifiers($event => (_ctx.setSystemProcessSort('memory')), ["stop"]))
                                }, {
                                  default: _withCtx(() => [
                                    _createTextVNode(_toDisplayString(_ctx.translate('systemProcess.sortMemory')), 1 /* TEXT */)
                                  ]),
                                  _: 1 /* STABLE */
                                }, 8 /* PROPS */, ["type"]),
                                _createVNode(_component_el_button, {
                                  size: "small",
                                  type: _ctx.systemProcessSort === 'user' ? 'primary' : 'default',
                                  onClick: _cache[9] || (_cache[9] = _withModifiers($event => (_ctx.setSystemProcessSort('user')), ["stop"]))
                                }, {
                                  default: _withCtx(() => [
                                    _createTextVNode(_toDisplayString(_ctx.translate('systemProcess.sortUser')), 1 /* TEXT */)
                                  ]),
                                  _: 1 /* STABLE */
                                }, 8 /* PROPS */, ["type"])
                              ]),
                              _: 1 /* STABLE */
                            })
                          ])
                        ]),
                        default: _withCtx(() => [
                          _createElementVNode("p", _hoisted_49, _toDisplayString(_ctx.translate(_ctx.systemProcessSort === 'user' ? 'systemProcess.userNote' : 'systemProcess.note')), 1 /* TEXT */),
                          (_ctx.systemProcessSort !== 'user')
                            ? (_openBlock(), _createElementBlock("div", _hoisted_50, [
                                _createVNode(_component_el_table, {
                                  data: _ctx.sortedSystemProcesses,
                                  size: "small",
                                  "empty-text": _ctx.translate('systemProcess.empty'),
                                  "max-height": "520"
                                }, {
                                  default: _withCtx(() => [
                                    _createVNode(_component_el_table_column, {
                                      label: _ctx.translate('systemProcess.instances'),
                                      width: "110"
                                    }, {
                                      default: _withCtx((scope) => [
                                        _createElementVNode("span", {
                                          title: _ctx.formatProcessPids(scope.row)
                                        }, _toDisplayString(_ctx.formatProcessInstances(scope.row)), 9 /* TEXT, PROPS */, _hoisted_51)
                                      ]),
                                      _: 1 /* STABLE */
                                    }, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      prop: "username",
                                      label: _ctx.translate('process.user'),
                                      width: "130",
                                      "show-overflow-tooltip": ""
                                    }, null, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      prop: "name",
                                      label: _ctx.translate('process.name'),
                                      "min-width": "150",
                                      "show-overflow-tooltip": ""
                                    }, null, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      label: _ctx.translate('systemProcess.cpu'),
                                      width: "105",
                                      align: "right"
                                    }, {
                                      default: _withCtx((scope) => [
                                        _createTextVNode(_toDisplayString(_ctx.formatPercent(scope.row.cpu_percent, 1)), 1 /* TEXT */)
                                      ]),
                                      _: 1 /* STABLE */
                                    }, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      label: _ctx.translate('systemProcess.memory'),
                                      width: "150",
                                      align: "right"
                                    }, {
                                      default: _withCtx((scope) => [
                                        _createTextVNode(_toDisplayString(_ctx.formatBytes(scope.row.memory_bytes)) + " · " + _toDisplayString(_ctx.formatPercent(scope.row.memory_percent, 1)), 1 /* TEXT */)
                                      ]),
                                      _: 1 /* STABLE */
                                    }, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      prop: "command",
                                      label: _ctx.translate('process.command'),
                                      "min-width": "320",
                                      "show-overflow-tooltip": ""
                                    }, {
                                      default: _withCtx((scope) => [
                                        _createElementVNode("code", null, _toDisplayString(scope.row.command), 1 /* TEXT */)
                                      ]),
                                      _: 1 /* STABLE */
                                    }, 8 /* PROPS */, ["label"])
                                  ]),
                                  _: 1 /* STABLE */
                                }, 8 /* PROPS */, ["data", "empty-text"])
                              ]))
                            : (_openBlock(), _createElementBlock("div", _hoisted_52, [
                                _createVNode(_component_el_table, {
                                  data: _ctx.systemUsers,
                                  size: "small",
                                  "empty-text": _ctx.translate('systemProcess.emptyUser'),
                                  "max-height": "520",
                                  "default-sort": { prop: 'cpu_percent', order: 'descending' }
                                }, {
                                  default: _withCtx(() => [
                                    _createVNode(_component_el_table_column, {
                                      prop: "username",
                                      label: _ctx.translate('process.user'),
                                      "min-width": "170",
                                      "show-overflow-tooltip": ""
                                    }, null, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      prop: "cpu_percent",
                                      label: _ctx.translate('systemProcess.cpu'),
                                      width: "150",
                                      align: "right",
                                      sortable: ""
                                    }, {
                                      default: _withCtx((scope) => [
                                        _createTextVNode(_toDisplayString(_ctx.formatPercent(scope.row.cpu_percent, 1)), 1 /* TEXT */)
                                      ]),
                                      _: 1 /* STABLE */
                                    }, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      prop: "memory_bytes",
                                      label: _ctx.translate('systemProcess.memory'),
                                      width: "180",
                                      align: "right",
                                      sortable: ""
                                    }, {
                                      default: _withCtx((scope) => [
                                        _createTextVNode(_toDisplayString(_ctx.formatBytes(scope.row.memory_bytes)) + " · " + _toDisplayString(_ctx.formatPercent(scope.row.memory_percent, 1)), 1 /* TEXT */)
                                      ]),
                                      _: 1 /* STABLE */
                                    }, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      prop: "process_group_count",
                                      label: _ctx.translate('systemProcess.groups'),
                                      width: "130",
                                      align: "right"
                                    }, null, 8 /* PROPS */, ["label"]),
                                    _createVNode(_component_el_table_column, {
                                      prop: "instance_count",
                                      label: _ctx.translate('systemProcess.instanceCount'),
                                      width: "130",
                                      align: "right"
                                    }, null, 8 /* PROPS */, ["label"])
                                  ]),
                                  _: 1 /* STABLE */
                                }, 8 /* PROPS */, ["data", "empty-text"])
                              ])),
                          (_ctx.systemProcessSort !== 'user')
                            ? (_openBlock(), _createElementBlock("div", _hoisted_53, [
                                (!_ctx.sortedSystemProcesses.length)
                                  ? (_openBlock(), _createElementBlock("div", _hoisted_54, _toDisplayString(_ctx.translate('systemProcess.empty')), 1 /* TEXT */))
                                  : _createCommentVNode("v-if", true),
                                (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.sortedSystemProcesses, (process) => {
                                  return (_openBlock(), _createElementBlock("article", {
                                    key: `system-${process.username}-${process.name}-${process.command}`,
                                    class: "process-card"
                                  }, [
                                    _createElementVNode("div", _hoisted_55, [
                                      _createElementVNode("strong", null, _toDisplayString(process.name), 1 /* TEXT */),
                                      _createElementVNode("span", {
                                        title: _ctx.formatProcessPids(process)
                                      }, _toDisplayString(_ctx.formatProcessInstances(process)), 9 /* TEXT, PROPS */, _hoisted_56)
                                    ]),
                                    _createElementVNode("dl", null, [
                                      _createElementVNode("div", null, [
                                        _createElementVNode("dt", null, _toDisplayString(_ctx.translate('process.user')), 1 /* TEXT */),
                                        _createElementVNode("dd", null, _toDisplayString(process.username), 1 /* TEXT */)
                                      ]),
                                      _createElementVNode("div", null, [
                                        _createElementVNode("dt", null, _toDisplayString(_ctx.translate('systemProcess.cpu')), 1 /* TEXT */),
                                        _createElementVNode("dd", null, _toDisplayString(_ctx.formatPercent(process.cpu_percent, 1)), 1 /* TEXT */)
                                      ]),
                                      _createElementVNode("div", null, [
                                        _createElementVNode("dt", null, _toDisplayString(_ctx.translate('systemProcess.memory')), 1 /* TEXT */),
                                        _createElementVNode("dd", null, _toDisplayString(_ctx.formatBytes(process.memory_bytes)) + " · " + _toDisplayString(_ctx.formatPercent(process.memory_percent, 1)), 1 /* TEXT */)
                                      ]),
                                      _createElementVNode("div", _hoisted_57, [
                                        _createElementVNode("dt", null, _toDisplayString(_ctx.translate('process.command')), 1 /* TEXT */),
                                        _createElementVNode("dd", null, [
                                          _createElementVNode("code", null, _toDisplayString(process.command), 1 /* TEXT */)
                                        ])
                                      ])
                                    ])
                                  ]))
                                }), 128 /* KEYED_FRAGMENT */))
                              ]))
                            : (_openBlock(), _createElementBlock("div", _hoisted_58, [
                                (!_ctx.systemUsers.length)
                                  ? (_openBlock(), _createElementBlock("div", _hoisted_59, _toDisplayString(_ctx.translate('systemProcess.emptyUser')), 1 /* TEXT */))
                                  : _createCommentVNode("v-if", true),
                                (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.systemUsers, (user) => {
                                  return (_openBlock(), _createElementBlock("article", {
                                    key: `system-user-${user.username}`,
                                    class: "process-card"
                                  }, [
                                    _createElementVNode("div", _hoisted_60, [
                                      _createElementVNode("strong", null, _toDisplayString(user.username), 1 /* TEXT */),
                                      _createElementVNode("span", null, _toDisplayString(_ctx.formatPercent(user.cpu_percent, 1)), 1 /* TEXT */)
                                    ]),
                                    _createElementVNode("dl", null, [
                                      _createElementVNode("div", null, [
                                        _createElementVNode("dt", null, _toDisplayString(_ctx.translate('systemProcess.memory')), 1 /* TEXT */),
                                        _createElementVNode("dd", null, _toDisplayString(_ctx.formatBytes(user.memory_bytes)) + " · " + _toDisplayString(_ctx.formatPercent(user.memory_percent, 1)), 1 /* TEXT */)
                                      ]),
                                      _createElementVNode("div", null, [
                                        _createElementVNode("dt", null, _toDisplayString(_ctx.translate('systemProcess.groups')), 1 /* TEXT */),
                                        _createElementVNode("dd", null, _toDisplayString(user.process_group_count), 1 /* TEXT */)
                                      ]),
                                      _createElementVNode("div", null, [
                                        _createElementVNode("dt", null, _toDisplayString(_ctx.translate('systemProcess.instanceCount')), 1 /* TEXT */),
                                        _createElementVNode("dd", null, _toDisplayString(user.instance_count), 1 /* TEXT */)
                                      ])
                                    ])
                                  ]))
                                }), 128 /* KEYED_FRAGMENT */))
                              ]))
                        ]),
                        _: 1 /* STABLE */
                      })
                    ]),
                    _: 1 /* STABLE */
                  })
                ])
              ]),
              _createElementVNode("section", _hoisted_61, [
                _createElementVNode("div", _hoisted_62, [
                  _createElementVNode("div", null, [
                    _cache[18] || (_cache[18] = _createElementVNode("span", { class: "eyebrow" }, "Accelerators", -1 /* CACHED */)),
                    _createElementVNode("h2", _hoisted_63, _toDisplayString(_ctx.translate('gpu.title')), 1 /* TEXT */)
                  ]),
                  _createElementVNode("span", _hoisted_64, _toDisplayString(_ctx.translate('units.cards', _ctx.gpuList.length)), 1 /* TEXT */)
                ]),
                (_ctx.gpuList.length)
                  ? (_openBlock(), _createElementBlock("div", _hoisted_65, [
                      (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(_ctx.gpuList, (gpu) => {
                        return (_openBlock(), _createElementBlock("article", {
                          key: gpu.uuid || gpu.index,
                          class: "panel gpu-card"
                        }, [
                          _createElementVNode("header", _hoisted_66, [
                            _createElementVNode("div", _hoisted_67, [
                              _createElementVNode("span", _hoisted_68, "GPU " + _toDisplayString(gpu.index), 1 /* TEXT */),
                              _createElementVNode("h3", null, _toDisplayString(gpu.name), 1 /* TEXT */)
                            ]),
                            _createVNode(_component_el_tag, {
                              type: _ctx.getTemperatureState(gpu.temperature).type,
                              effect: "light",
                              round: ""
                            }, {
                              default: _withCtx(() => [
                                _createElementVNode("span", _hoisted_69, _toDisplayString(_ctx.formatTemperature(gpu.temperature)), 1 /* TEXT */)
                              ]),
                              _: 2 /* DYNAMIC */
                            }, 1032 /* PROPS, DYNAMIC_SLOTS */, ["type"])
                          ]),
                          _createElementVNode("div", _hoisted_70, [
                            _createElementVNode("div", _hoisted_71, [
                              _createElementVNode("div", _hoisted_72, [
                                _createElementVNode("div", _hoisted_73, [
                                  _createElementVNode("span", null, _toDisplayString(_ctx.translate('gpu.utilization')), 1 /* TEXT */),
                                  _createElementVNode("strong", null, _toDisplayString(_ctx.formatPercent(gpu.utilization.gpu)), 1 /* TEXT */)
                                ]),
                                _createVNode(_component_el_progress, {
                                  percentage: Math.round(gpu.utilization.gpu),
                                  "stroke-width": 14,
                                  "show-text": false
                                }, null, 8 /* PROPS */, ["percentage"])
                              ]),
                              _createElementVNode("div", _hoisted_74, [
                                _createElementVNode("div", _hoisted_75, [
                                  _createElementVNode("span", null, _toDisplayString(_ctx.translate('gpu.vram')), 1 /* TEXT */),
                                  _createElementVNode("strong", null, _toDisplayString(_ctx.formatBytes(gpu.memory.used)) + " / " + _toDisplayString(_ctx.formatBytes(gpu.memory.total)), 1 /* TEXT */)
                                ]),
                                _createVNode(_component_el_progress, {
                                  percentage: gpu.memory.percent,
                                  "stroke-width": 14,
                                  "show-text": false
                                }, null, 8 /* PROPS */, ["percentage"])
                              ])
                            ]),
                            _createElementVNode("div", _hoisted_76, [
                              _createElementVNode("div", _hoisted_77, [
                                _createElementVNode("span", null, _toDisplayString(_ctx.translate('gpu.temperature')), 1 /* TEXT */),
                                _createElementVNode("strong", {
                                  class: _normalizeClass('text-' + _ctx.getTempStatus(gpu.temperature).key)
                                }, _toDisplayString(_ctx.formatTemperature(gpu.temperature)), 3 /* TEXT, CLASS */)
                              ]),
                              _createElementVNode("div", _hoisted_78, [
                                _createElementVNode("span", null, _toDisplayString(_ctx.translate('gpu.power')), 1 /* TEXT */),
                                _createElementVNode("strong", null, _toDisplayString(_ctx.formatPower(gpu.power.usage)), 1 /* TEXT */)
                              ]),
                              _createElementVNode("div", _hoisted_79, [
                                _createElementVNode("span", null, _toDisplayString(_ctx.translate('gpu.fan')), 1 /* TEXT */),
                                _createElementVNode("strong", null, _toDisplayString(_ctx.formatPercent(gpu.fan_speed)), 1 /* TEXT */)
                              ]),
                              _createElementVNode("div", _hoisted_80, [
                                _createElementVNode("span", null, _toDisplayString(_ctx.translate('gpu.memoryUtil')), 1 /* TEXT */),
                                _createElementVNode("strong", null, _toDisplayString(_ctx.formatPercent(gpu.utilization.memory)), 1 /* TEXT */)
                              ])
                            ])
                          ]),
                          _createVNode(_component_el_collapse, { class: "process-collapse" }, {
                            default: _withCtx(() => [
                              _createVNode(_component_el_collapse_item, {
                                name: `gpu-${gpu.index}`
                              }, {
                                title: _withCtx(() => [
                                  _createElementVNode("span", _hoisted_81, [
                                    _createElementVNode("strong", null, _toDisplayString(_ctx.translate('process.title')), 1 /* TEXT */),
                                    _createElementVNode("span", null, _toDisplayString(_ctx.translate('process.count', gpu.process_count)), 1 /* TEXT */)
                                  ])
                                ]),
                                default: _withCtx(() => [
                                  _createElementVNode("div", _hoisted_82, [
                                    _createVNode(_component_el_table, {
                                      data: gpu.processes,
                                      size: "small",
                                      "empty-text": _ctx.translate('process.empty')
                                    }, {
                                      default: _withCtx(() => [
                                        _createVNode(_component_el_table_column, {
                                          prop: "pid",
                                          label: _ctx.translate('process.pid'),
                                          width: "86"
                                        }, null, 8 /* PROPS */, ["label"]),
                                        _createVNode(_component_el_table_column, {
                                          prop: "username",
                                          label: _ctx.translate('process.user'),
                                          width: "120",
                                          "show-overflow-tooltip": ""
                                        }, null, 8 /* PROPS */, ["label"]),
                                        _createVNode(_component_el_table_column, {
                                          label: _ctx.translate('process.memory'),
                                          width: "120"
                                        }, {
                                          default: _withCtx((scope) => [
                                            _createTextVNode(_toDisplayString(_ctx.formatBytes(scope.row.gpu_memory)), 1 /* TEXT */)
                                          ]),
                                          _: 1 /* STABLE */
                                        }, 8 /* PROPS */, ["label"]),
                                        _createVNode(_component_el_table_column, {
                                          prop: "command",
                                          label: _ctx.translate('process.command'),
                                          "min-width": "280",
                                          "show-overflow-tooltip": ""
                                        }, {
                                          default: _withCtx((scope) => [
                                            _createElementVNode("code", null, _toDisplayString(scope.row.command), 1 /* TEXT */)
                                          ]),
                                          _: 1 /* STABLE */
                                        }, 8 /* PROPS */, ["label"])
                                      ]),
                                      _: 1 /* STABLE */
                                    }, 8 /* PROPS */, ["data", "empty-text"])
                                  ]),
                                  _createElementVNode("div", _hoisted_83, [
                                    (!gpu.processes.length)
                                      ? (_openBlock(), _createElementBlock("div", _hoisted_84, _toDisplayString(_ctx.translate('process.empty')), 1 /* TEXT */))
                                      : _createCommentVNode("v-if", true),
                                    (_openBlock(true), _createElementBlock(_Fragment, null, _renderList(gpu.processes, (process) => {
                                      return (_openBlock(), _createElementBlock("article", {
                                        key: `${gpu.uuid}-${process.pid}`,
                                        class: "process-card"
                                      }, [
                                        _createElementVNode("div", _hoisted_85, [
                                          _createElementVNode("strong", null, "PID " + _toDisplayString(process.pid), 1 /* TEXT */),
                                          _createElementVNode("span", null, _toDisplayString(_ctx.formatBytes(process.gpu_memory)), 1 /* TEXT */)
                                        ]),
                                        _createElementVNode("dl", null, [
                                          _createElementVNode("div", null, [
                                            _createElementVNode("dt", null, _toDisplayString(_ctx.translate('process.user')), 1 /* TEXT */),
                                            _createElementVNode("dd", null, _toDisplayString(process.username), 1 /* TEXT */)
                                          ]),
                                          _createElementVNode("div", _hoisted_86, [
                                            _createElementVNode("dt", null, _toDisplayString(_ctx.translate('process.command')), 1 /* TEXT */),
                                            _createElementVNode("dd", null, [
                                              _createElementVNode("code", null, _toDisplayString(process.command), 1 /* TEXT */)
                                            ])
                                          ])
                                        ])
                                      ]))
                                    }), 128 /* KEYED_FRAGMENT */))
                                  ])
                                ]),
                                _: 2 /* DYNAMIC */
                              }, 1032 /* PROPS, DYNAMIC_SLOTS */, ["name"])
                            ]),
                            _: 2 /* DYNAMIC */
                          }, 1024 /* DYNAMIC_SLOTS */)
                        ]))
                      }), 128 /* KEYED_FRAGMENT */))
                    ]))
                  : (_openBlock(), _createElementBlock("div", _hoisted_87, [
                      _createVNode(_component_el_icon, null, {
                        default: _withCtx(() => [
                          _createVNode(_component_Monitor)
                        ]),
                        _: 1 /* STABLE */
                      }),
                      _createElementVNode("div", null, [
                        _createElementVNode("h3", null, _toDisplayString(_ctx.translate('gpu.emptyTitle')), 1 /* TEXT */),
                        _createElementVNode("p", null, _toDisplayString(_ctx.translate('gpu.emptyDesc')), 1 /* TEXT */)
                      ])
                    ]))
              ])
            ], 64 /* STABLE_FRAGMENT */))
          : (_ctx.loading || _ctx.configLoading)
            ? (_openBlock(), _createElementBlock("section", _hoisted_88, [
                _createVNode(_component_el_skeleton, { animated: "" }, {
                  template: _withCtx(() => [
                    _createElementVNode("div", _hoisted_89, [
                      (_openBlock(), _createElementBlock(_Fragment, null, _renderList(6, (n) => {
                        return _createVNode(_component_el_skeleton_item, {
                          key: n,
                          variant: "rect",
                          class: "skeleton-card"
                        })
                      }), 64 /* STABLE_FRAGMENT */))
                    ]),
                    _createVNode(_component_el_skeleton_item, {
                      variant: "rect",
                      class: "skeleton-panel"
                    })
                  ]),
                  _: 1 /* STABLE */
                })
              ]))
            : (_ctx.nodeError)
              ? (_openBlock(), _createElementBlock("section", _hoisted_90, [
                  _createVNode(_component_el_icon, null, {
                    default: _withCtx(() => [
                      _createVNode(_component_WarningFilled)
                    ]),
                    _: 1 /* STABLE */
                  }),
                  _createElementVNode("div", null, [
                    _createElementVNode("h2", null, _toDisplayString(_ctx.translate('errors.nodeFailedTitle')), 1 /* TEXT */),
                    _createElementVNode("p", null, _toDisplayString(_ctx.translate('errors.nodeFailedDesc')), 1 /* TEXT */)
                  ]),
                  _createVNode(_component_el_button, {
                    type: "primary",
                    onClick: _ctx.refreshCurrent
                  }, {
                    default: _withCtx(() => [
                      _createTextVNode(_toDisplayString(_ctx.translate('retry')), 1 /* TEXT */)
                    ]),
                    _: 1 /* STABLE */
                  }, 8 /* PROPS */, ["onClick"])
                ]))
              : _createCommentVNode("v-if", true)
    ]),
    _createElementVNode("footer", _hoisted_91, [
      _createElementVNode("p", null, _toDisplayString(_ctx.translate('footer.line1')), 1 /* TEXT */)
    ])
  ], 64 /* STABLE_FRAGMENT */))
}
})(Vue);
