import { createHash } from 'node:crypto';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from '@vue/compiler-dom';

const rootDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const frontDir = join(rootDir, 'front');
const indexPath = join(frontDir, 'index.html');
const renderPath = join(frontDir, 'app.render.js');
const runtimeSource = join(rootDir, 'node_modules', 'vue', 'dist', 'vue.runtime.global.prod.js');
const runtimeTarget = join(frontDir, 'vendor', 'vue.runtime.global.prod.js');
const checkOnly = process.argv.includes('--check');

const indexHtml = await readFile(indexPath, 'utf8');
const mountStart = indexHtml.indexOf('<div id="app"');
const templateStart = indexHtml.indexOf('>', mountStart) + 1;
const appScriptStart = indexHtml.indexOf('\n  <script src="app.render.js', templateStart);
const mountEnd = indexHtml.lastIndexOf('</div>', appScriptStart);

if (mountStart < 0 || templateStart <= mountStart || appScriptStart < 0 || mountEnd <= templateStart) {
  throw new Error('Unable to locate the #app template in front/index.html');
}

const template = indexHtml.slice(templateStart, mountEnd).trim();
const templateHash = createHash('sha256').update(template).digest('hex');
const { code } = compile(template, {
  mode: 'function',
  prefixIdentifiers: true,
  hoistStatic: true,
  cacheHandlers: true,
  comments: false,
});

const generatedRender = `// Generated by scripts/build-front.mjs. Do not edit directly.\n` +
  `// Template SHA-256: ${templateHash}\n` +
  `window.GpuMonitorRender = ((Vue) => {\n${code}\n})(Vue);\n`;

const runtimeSourceText = await readFile(runtimeSource, 'utf8');
const servedScripts = new Map([
  ['front/app.js', await readFile(join(frontDir, 'app.js'), 'utf8')],
  ['front/app.render.js', generatedRender],
  ['front/vendor/vue.runtime.global.prod.js', runtimeSourceText],
  ['front/vendor/element-plus.js', await readFile(join(frontDir, 'vendor', 'element-plus.js'), 'utf8')],
  ['front/vendor/element-plus-icons.js', await readFile(join(frontDir, 'vendor', 'element-plus-icons.js'), 'utf8')],
]);

for (const [path, source] of servedScripts) {
  if (/\b(?:eval|Function)\s*\(/.test(source)) {
    throw new Error(`${path} contains dynamic code execution`);
  }
}

if (checkOnly) {
  const [currentRender, currentRuntime] = await Promise.all([
    readFile(renderPath, 'utf8'),
    readFile(runtimeTarget, 'utf8'),
  ]);
  if (currentRender !== generatedRender) throw new Error('front/app.render.js is stale; run npm run build:front');
  if (currentRuntime !== runtimeSourceText) throw new Error('Vue runtime-only vendor file is stale; run npm run build:front');
  console.log(`Front-end precompile check passed (${templateHash.slice(0, 12)})`);
} else {
  await mkdir(dirname(runtimeTarget), { recursive: true });
  await Promise.all([
    writeFile(renderPath, generatedRender),
    copyFile(runtimeSource, runtimeTarget),
  ]);
  console.log(`Precompiled front-end template (${templateHash.slice(0, 12)})`);
}
